import 'package:get/get.dart';
import 'package:rohandrayhan/Utils/translation_key.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      greetingWord:"Hello",
      requiredFiled:"This field is required",
      invalidEmail:"This e-mail is invalid",
      invalidPassword:"This password is invalid",
      tryAgain:"Please try again later",
      noInternet:"There's no internet connection",
      openInternet:"Please open your internet and try again",
      location:"The location",
      locationRequired:"The location is required so you can continue",
      error:"There's error happen please try again later",
      phoneNumberError:"This phone number is not valid",
      invalidReTypePassword:"passwords does not match",
      enterPasswordFirst:"You must enter the password first",
      refreshKey:"Refresh",
      cameraSource1:"take a picture",
      cameraSource2:"Choose a photo from the photo gallery",
      welcomeText:"Welcome",
      welcomeText1:"Here We Can Help you save your time",
      welcomeText2:"while asking for a medical help",
      welcomeBTN1:"Login",
      welcomeBTN2:"Register Now",
      skipToHomeBTN: "skip to home >",
      signUpTitle: "Sign Up",
      signUpTitleName: "Enter Your Full Name",
      signUpTextName1: "First",
      signUpTextName2: "Middle",
      signUpTextName3: "Last",
      signUpTitlePhone: "Enter Your Phone Number",
      signUpTextPhone: "123-4567-8",
      signUpTextPhoneKey:"+974",
      signUpTitleEmail: "Enter Your Email",
      signUpTextEmail: "example@example.com",
      signUpTitlePass: "Enter Your Password",
      signUpTitleConfirmPass: "Confirm Your Password",
      signUpBTN: "Sign Up",
      signUpText1: "Already have an account?",
      signUpText2: "Sign In",
      historyTitle: "My Transactions",
      historyTag1: "Clinic Detection",
      historyTag2: "home visits",
      noHistoryDataHosp: "There is no previous history for clinic statements",
      noHistoryDataHome: "There is no previous history of home visits",
      visitHasBeenFinished: "Finished",
      visitHasBeenCanceled: "Cancelled",
      noPointEarned: "No points were earned for this visit",
      pointEarnedText1: "Points Earned:",
      pointEarnedText2: "point",
      reReservationBTN: "Reservation",
      showDoctorReportBTN: "Medical Report",
      reviewVisitBTN: "Review",
      reviewWarning:"A comment has already been added about the visit. If you want to delete or modify the comment, you can contact the application management",
      homeAnalysis: "Home Detection",
      clinicAnalysis: "Clinic Detection",
      goBack:"Back",
      doctorReport: "Doctor's Report",
      noDoctorReport:"No doctor's report has been submitted yet",
      searchForDoctor:"Find a Doctor",
      searchWithDoctorName:"Search With Doctor Name",
      anotherSpecialty:"Other Specialties",
      mostChosenSpecialty:"Most Chosen Specialties",
      errorKey: "An error occurred",
      doctorRating:"Doctor Rating:",
      hospRating:"Hospital Rating:",
      comment: "comment",
      addReview:"Add Comment",
      commentSuccess:"Comment Uploaded Successfully",
      warningKey: "warning",
      mustChooseReservationDate: "You must choose the reservation date",
      mustChooseReservationTime: "You must choose a reservation time",
      goToReg: 'go to register',
      contWithoutAcc: 'continue without counting',
      patientNameWarning: "The patient's name must be entered",
      patientPhoneWarning: "The patient's mobile number must be entered",
      losePointWarning: 'You will lose the points earned if you do not log in or do not create an account',
      noTimeAvailable:"There is no time available on this date",
      nameKey:"Name",
      phoneKey:"Mobile Number",
      makeReservation: "Confirm privilege appointment",
      reservationSuccess1:"Doctor has been booked ",
      reservationSuccess2: " successfully",
      reservationDate: "Day",
      reservationTime: "time",
      nextPageBTN: "Next",
      extraDataTitle: "Additional Doctor Information",
      extraDataText: "(Option)",
      extraDataAgeTitle: "Age",
      extraDataGenderTitle: "Gender",
      extraDataGenderMale: "Male",
      extraDataGenderFemale: "Female",
      extraDataComment: "Symptoms",
      extraDataFileTitle: "Files",
      extraDataCommentText:"such as cough, backache, etc",
      extraDataFileText:"Add Files",
      reservationNoDateAvailable:"There are currently no dates available",
      firstReservationTitle:"Select a reservation date",
      secondReservationTitle: "Confirm privilege appointment",
      reservationForAnotherOne: "I am making a reservation on behalf of another patient",
      reservationForAnotherOnePhone: "Mobile Number",
      reservationForAnotherOneName: "Full Name",
      secondReservationBTN:"Confirm privilege appointment",
      currencyKey: "riyal",
      reservationPrice: "Reservation Price",
      notRegisterUserProfile: "You must log in or create an account to have a personal account and activate some features",
      signInProfile: "Login",
      signUpProfile: "Create Account",
      profileTag1: "Profile Update",
      profileTag2: "medical insurance",
      profileTag3: "Technical Support (Chat)",
      profileTag12: "Technical Support (WhatApp)",
      profileTag4: "My Transaction History",
      profileTag5: "Change Password",
      profileTag6: "Favorite",
      profileTag7: "Change language",
      profileTag8: "Privacy Policy",
      profileTag9: "Terms and Conditions",
      profileTag10: "App Rating",
      profileTag11: "exit",
      signInTitle:  "Sign In",
      signInText1:  "Hello",
      signInText2: "Sign into your account",
      signInTextEmail: "Email",
      signInTextPass: "Password",
      signInTextForgetPass: "Forget Your Password",
      signInTextBTN: "Login",
      insuranceDataTitle: "Health Insurance Data",
      insuranceNoData: "There is no data on record for health insurance",
      insuranceAddData: "Add health insurance card",
      insuranceDataCompName: "Insurance Company Name:",
      insuranceDataNum: "Insurance Card Number:",
      insuranceDataEdit: "Modify health insurance card information",
      insuranceDataEditNameTitle: "Enter the name of the insurance company",
      insuranceDataEditNameText: "Insurance Company",
      insuranceDataEditNumTitle: "Enter the insurance card number",
      hospDetailsTitle: "Hospital Data",
      addToFavText: 'It can only be added to favorites when logging in or creating an account',
      hospCategoryTitle1: "Doctors",
      hospCategoryText1: "Doctor",
      hospCategoryTitle2: "Majors",
      hospCategoryText2: "Major",
      hospCategoryTitle3: "Analyses",
      hospCategoryTitle4:"Radiology",
      aboutHospKey: "About the Hospital",
      moreDetailsHosp: "View More Details",
      noDoctorDataHosp:"No doctors are registered in the hospital yet",
      addToFavoriteBTN: "Add to Favourites",
      removeToFavoriteBTN: "Remove from Favourites",
      noHospData: "There are no hospitals registered here yet",
      noHospDataInSpec: "There are no hospitals listed for this specialty",
      showMoreDoctorsHome: "Show More Doctors",
      noHospAvailableHome: "There are no hospitals available right now",
      moreInfoHosp: "View Details",
      hospInfo: "About my hospital",
      notAvailableLink: "This link cannot be opened",
      chooseGov:"Choose City",
      forgetPassTitle:"Forgot Password",
      favTitle: 'Favorite List',
      favTap1: 'Doctors',
      favTap2: 'Hospitals',
      noDocFavData: "There are no doctors in the favourites",
      noHospFavData: "There is no hospital in the favorites list",
      removeDocFromFav1: "Doctor Removed",
      removeDocFromFav2: "From Favourites",
      editProfileTitle:"Update Profile",
      oneStarRat: "1 Star and More",
      twoStarRat: "2 Stars, One or More",
      threeStarRat: "3 Stars and More",
      fourStarRat: "4 Stars and More",
      fiveStarRat: "5 Stars",
      addDocToFav1: "Doctor added",
      addDocToFav2: "To Favorites",
      noSearchHospData: "There is no hospital for whom this information applies",
      noSearchDocData:"There is no doctor for whom this information applies",
      advancedSearchTitle: "Advanced Search",
      advancedSearchBTN: "Start Search",
      searchTypeTitle: "Search Type:",
      searchType1: "Hospital",
      searchType2: "Doctor",
      searchAreaTitle:"Search Area:",
      searchAreaText1: "Select the area to search",
      searchAreaText2: "Selected Area:",
      searchSpecTitle:"Specific Specialization for Search:",
      searchSpecText1:"Select the specialty you want to search",
      searchSpecText2:"Selected Major:",
      searchLevelTitle: "Select Doctor Level:",
      searchLevelText1: "Select the doctor level you want to search",
      searchLevelText2: "Doctor Level:",
      searchPriceTitle: "Select a price range to display:",
      searchPriceText1: "Start Price",
      searchPriceText2: "Final Price",
      searchRateTitle: "Choose the rating level:",
      searchRateText1: "Select the doctor level you want to search",
      searchRateText2: "Rate Level:",
      searchReservationTypeTitle: "Disclosure Type:",
      searchReservationTypeText1: "Home List",
      searchReservationTypeText2: "Disclosure in Clinic",
      loadingKey: "loading",
      doctorHasNoScreen1: "There are no specialist doctors registered in this specialty yet",
      doctorHasNoScreen2: "There is no doctor with that name",
      doctorHasNoScreen3: "There are no doctors in this area",
      doctorHasNoScreen4: "There are no doctors with that name in this area",
      allAreaKey: "All Areas",
      noReviewsOnDoc: "There are no reviews for this doctor yet",
      reviewsOnDoc1: "Overall Rating From",
      reviewsOnDoc2: "Guest",
      docAchievement1: "A good listener",
      docAchievement2:"Detailed Explanation",
      reservationPrice1: "Disclosure:",
      reservationPrice2: "SAR",
      reservationTime1: "Waiting time:",
      reservationTime2: "Minute Minute",
      noTimeAvailableDocScreen: "There are no times available yet",
      reservationBTNDocScreen: "Book Now",
      availableToDay: "Available Today From",
      doctorLoc: "Doctor's Location",
      docReview:"Doctor's Assessment",
      toKey:"to",
      waitingTimeDocDetailedScreenText1: "minute",
      waitingTimeDocDetailedScreenText2: "waiting time",
      priceDocDetailedScreenText1: "SAR",
      priceDocDetailedScreenText2: "Reservation Price",
      showOnGoogleMap: "Open the location of the place on Google Maps",
      noVideo: "There is no video available at this time",
      noTimeDocDetailedScreen: "There are no times available at this time",
      timeDocDetailedScreenText1: "Select your reservation time",
      timeDocDetailedScreenText2: "First-come-first-served",
      pointDocDetailedScreenText1: "You will get",
      pointDocDetailedScreenText2: "point on hold",
      doctorReview: "Doctor Review",
      placeReview: "Hospital Review",
      doctorInformation: "Doctor Information",
      noReviews: "There are no comments",
      doctorReviewsTitle: "Visitor Reviews",
      doctorDetailedTitle:"Doctor's Data",
      changePassScreenTitle: "Change Password",
      changePassScreenText1: "New Password",
      changePassScreenText2: "Retype your new password",
      changePassScreenText3: "The password must contain an uppercase letter, a lowercase letter, and special characters such as :(@,#,!,&,*,~) and a number and not less than 8 characters long",
      deleteAcc: 'Delete account',
      logOut: 'Log out of account',
      warningLogOut: 'Log out of account',
      warningDeleteAcc: "Deleting the account will result in the loss of all registered data as well as the loss of the points gained",
      contDeleteAcc:"Complete Deleting",
      bottomBarItem1: "Account",
      bottomBarItem2: "Doctors",
      bottomBarItem3: "Home",
      bottomBarItem4: "Hospital",
      bottomBarItem5: "Advanced Search",
      languageDialogueEN: " English ",
      languageDialogueAR: " Arabic ",
      languageDialogueCL: "Choose Language",
      languageDialogueBTN:"Change Language",
      languageWelcomeBTN:"تغير اللغه إلى اللغة العربية",
      addHospToFavText1: "The hospital has been added",
      addHospToFavText2: "To the favorites list",
      removeHospToFavText1: "The hospital has been deleted",
      removeHospToFavText2: "from favorites list",
    },
    "ar": {
      greetingWord:"اهلا وسهلا بك",
      requiredFiled:"هذه الخانة مطلوبه",
      invalidEmail:"هذا البريد الإلكتروني غير صالح",
      invalidPassword:"كلمة السر هذه غير صالحة",
      tryAgain:"الرجاء معاودة المحاولة في وقت لاحق",
      noInternet:"لا يوجد اتصال بالإنترنت",
      openInternet:"الرجاء فتح الإنترنت الخاص بك وحاول مرة أخرى",
      location:"الموقع",
      locationRequired:"الموقع مطلوب حتى تتمكن من المتابعة",
      error:"حدث خطأ ، يرجى المحاولة مرة أخرى لاحقًا",
      phoneNumberError:"رقم التلفون هذا غير صالح",
      invalidReTypePassword:"كلمه السر غير متطابقة",
      enterPasswordFirst:"يجب إدخال كلمه السر اولآ",
      refreshKey:"المحاوله مره اخرى",
      cameraSource1:"التقط صوره",
      cameraSource2:"اختيار صوره من معرض الصور",
      welcomeText:"مرحباً",
      welcomeText1: "هنا يمكننا مساعدتك في توفير وقتك",
      welcomeText2: "أثناء طلب المساعدة الطبية",
      welcomeBTN1: "تسجيل الدخول",
      welcomeBTN2: "سجل الآن",
      skipToHomeBTN: "انتقل إلى الصفحة الرئيسية>" ,
      signUpTitle: "تسجيل" ,
      signUpTitleName: "أدخل اسمك الكامل" ,
      signUpTextName1: "الأول" ,
      signUpTextName2: "الأوسط" ,
      signUpTextName3: "الأخير" ,
      signUpTitlePhone: "أدخل رقم هاتفك" ,
      signUpTextPhone: "123-4567-8" ,
      signUpTextPhoneKey: "+974" ,
      signUpTitleEmail: "أدخل بريدك الإلكتروني" ,
      signUpTextEmail: "example@example.com" ,
      signUpTitlePass: "أدخل كلمة المرور الخاصة بك" ,
      signUpTitleConfirmPass: "تأكيد كلمة المرور الخاصة بك" ,
      signUpBTN: "تسجيل",
      signUpText1: "هل لديك حساب بالفعل؟",
      signUpText2: "تسجيل الدخول" ,
      historyTitle: "معملاتى",
      historyTag1: "كشف عيادة",
      historyTag2: "زيارات منزليه",
      noHistoryDataHosp: "ليس هناك تاريخ سابق للكشوفات العياده",
      noHistoryDataHome: "ليس هناك تاريخ سابق للزيارات المنزليه",
      visitHasBeenFinished: "تم الإنتهاء",
      visitHasBeenCanceled: "تم الإلغاء",
      noPointEarned: "لم يتم اكتساب نقاط عن هذه الزياره",
      pointEarnedText1: "النقاط المكتسبه:",
      pointEarnedText2: "نقطه",
      reReservationBTN: "أعاده حجز",
      showDoctorReportBTN: "تقرير طبى",
      reviewVisitBTN: "تقيم",
      reviewWarning:"لقد تم اضافه تعليق بالفعل عن الزياره اذا تريد حذف التعليق او تعديله يمكنك التواصل مع إدارة التطبيق",
      homeAnalysis: "كشف المنزلى",
      clinicAnalysis:"كشف عيادة",
      goBack:"الرجوع",
      doctorReport:"تقرير الطبيب ",
      noDoctorReport:"لم يتم رفع تقرير من الطبيب حتى الأن",
      searchForDoctor:"ابحث عن دكتور",
      searchWithDoctorName:"ابحث باسم الدكتور",
      anotherSpecialty:"التخصصات الأخري",
      mostChosenSpecialty:"التخصصات الأكثر اختيارا",
      errorKey:"حدث خطأ",
      doctorRating:"تقيم الطبيب :",
      hospRating:"تقيم المستشفى :",
      comment: "التعليق",
      addReview:"أضف التعليق",
      commentSuccess:"تم رفع التعليق بنجاح",
      warningKey: "تحذير",
      mustChooseReservationDate: "يجب عليك اختيار تاريخ الحجز",
      mustChooseReservationTime: "يجب عليك ميعاد اختيار ميعاد الحجز",
      goToReg: 'الذهاب لتسجيل ',
      contWithoutAcc: ' الأستكمال دون حساب ',
      patientNameWarning: 'يجب كتابه اسم المريض',
      patientPhoneWarning:  'يجب كتابه رقم جوال المريض',
      losePointWarning: 'سوف تخسر النقاط المكتسبه فى حاله لم تسجل دخولك أو لم تنشاء حساب',
      noTimeAvailable:"ليس هناك ميعاد متاح فى هذا التاريخ",
      nameKey:"الاسم",
      phoneKey:"رقم الجوال",
      makeReservation:"تأكيد موعد الإمتياز",
      reservationSuccess1:"تم حجز الدكتور ",
      reservationSuccess2:" بنجاح ",
      reservationDate:  "اليوم",
      reservationTime: "الميعاد",
      nextPageBTN: "التالى",
      extraDataTitle:  "معلومات إضافية للدكتور",
      extraDataText: "(إختيار)",
      extraDataAgeTitle: "السن",
      extraDataGenderTitle: "النوع",
      extraDataGenderMale:  "الذكر",
      extraDataGenderFemale: "أنثى",
      extraDataComment: "الإعراض",
      extraDataFileTitle:  "ملفات",
      extraDataCommentText:"مثل الكحه ألام الظهر ما إلى ذلك",
      extraDataFileText:"أضف ملفات",
      reservationNoDateAvailable:"ليس هناك مواعيد متاحة الآن",
      firstReservationTitle:"اختار ميعاد الحجز",
      secondReservationTitle: "تأكيد موعد الإمتياز",
      reservationForAnotherOne: "أنا أقوم بالحجز نيابه عن مريض أخر",
      reservationForAnotherOnePhone: "رقم الجوال",
      reservationForAnotherOneName: "الإسم كامل",
      secondReservationBTN:"تأكيد موعد الإمتياز",
      currencyKey: " ريال",
      reservationPrice: "سعر الكشف",
      notRegisterUserProfile: "يجب تسجيل دخولك او انشاء حساب ليصبح ",
      signInProfile: "تسجيل الدخول",
      signUpProfile:  "إنشاء حساب",
      profileTag1: "تحديث الملف الشخصي",
      profileTag2: "تأمين طبي",
      profileTag3: "الدعم الفنى(شات)",
      profileTag12: "الدعم الفنى(واتس اب)",
      profileTag4: "تاريخ معملاتى",
      profileTag5: "تغيير كلمة المرور",
      profileTag6: "مفضل",
      profileTag7: "تغير اللغة",
      profileTag8:  "سياسة الخصوصية",
      profileTag9:  "الأحكام والشروط",
      profileTag10:  "تقييم التطبيق",
      profileTag11: "خروج",
      signInTitle: "تسجيل الدخول" ,
      signInText1: "مرحبًا" ,
      signInText2: "تسجيل الدخول إلى حسابك" ,
      signInTextEmail: "البريد الإلكتروني" ,
      signInTextPass: "كلمة المرور" ,
      signInTextForgetPass: "نسيت كلمة المرور" ,
      signInTextBTN: "تسجيل الدخول" ,
      insuranceDataTitle: "بينات التأمين الصحي",
      insuranceNoData: "ليس هناك بينات مسجله للتأمين الصحي",
      insuranceAddData: "اضافه بطاقه التأمين الصحى",
      insuranceDataCompName: "اسم شركه التأمين:",
      insuranceDataNum: "رقم بطاقة التأمين:",
      insuranceDataEdit: "تعديل بينات بطاقه التأمين الصحي",
      insuranceDataEditNameTitle: "ادخل اسم شركه التأمين",
      insuranceDataEditNameText: "شركه التأمين",
      insuranceDataEditNumTitle: "ادخل رقم بطاقة التأمين",
      hospDetailsTitle:  "بيانات المستشفي",
      addToFavText: 'لا يمكن الإضافة إلى قائمة المفضلة الا عند تسجيل الدخول او انشاء الحساب',
      hospCategoryTitle1: "الدكاترة",
      hospCategoryText1: "دكتور",
      hospCategoryTitle2: "التخصصات",
      hospCategoryText2: " تخصص",
      hospCategoryTitle3: "التحاليل",
      hospCategoryTitle4:"الأشعة",
      aboutHospKey: "عن المستشفي",
      moreDetailsHosp: "عرض المزيد من التفاصيل",
      noDoctorDataHosp:"لم يتم تسجيل اطباء فى المستشفى حتى الان",
      addHospToFavText1: "تم اضاف المستشفى",
      addHospToFavText2: "الى قائمة المفضلة",
      removeHospToFavText1: "تم حذف المستشفى",
      removeHospToFavText2: " من قائمة المفضله",
      hospLocation: "موقع المستشفى",
      addToFavoriteBTN: "أضف إلى المفضلة",
      removeToFavoriteBTN: "مسح من المفضله",
      noHospData: "ليس هنا مستشفيات مسجله حتى الان",
      noHospDataInSpec: "ليس هنا مستشفيات مسجله لهذا التخصص",
      showMoreDoctorsHome:  "عرض المزيد من الأطباء",
      noHospAvailableHome: "ليس هناك مستشفيات متاح الان",
      moreInfoHosp: "عرض التفاصيل",
      hospInfo:  " نبذه عن مسشفى",
      notAvailableLink: "لا يمكن فتح هذا الرابط",
      chooseGov:"أختر المدينة",
      forgetPassTitle:"نسيت كلمه المرور",
      favTitle: 'قائمة المفضلة',
      favTap1: 'أطباء',
      favTap2: 'مستشفيات',
      noDocFavData: "ليس هناك أطباء فى قائمة المفضلة",
      noHospFavData: "ليس هناك المستشفى فى قائمة المفضلة",
      removeDocFromFav1: "تم حذف الطبيب",
      removeDocFromFav2: "من قائمة المفضله",
      editProfileTitle:"تحديث الملف الشخصي",
      oneStarRat: "نجمة واحده واكثر",
      twoStarRat: "نجمتين واحده واكثر",
      threeStarRat: "ثلاث نجوم واكثر",
      fourStarRat: "اربع نجوم واكثر",
      fiveStarRat: "خمس نجوم",
      addDocToFav1: "تم اضاف الطبيب",
      addDocToFav2: "الى قائمة المفضلة",
      noSearchHospData:"ليس هناك مستشفى ينطبق عليه هذه المعلومات",
      noSearchDocData:"ليس هناك دكتور ينطبق عليه هذه المعلومات",
      advancedSearchTitle: "البحث المتقدم",
      advancedSearchBTN: "ابداء البحث",
      searchTypeTitle: "نوع البحث:",
      searchType1: "مستشفى",
      searchType2: "طبيب",
      searchAreaTitle:"منطقه البحث:",
      searchAreaText1:  "إختر المنطقة التى سوف يتم فيها البحث",
      searchAreaText2: "المنطقة المختاره:",
      searchSpecTitle:"التخصص المحدد للبحث :",
      searchSpecText1:"إختر التخصص الذى سوف يتم بناء البحث عليه",
      searchSpecText2:"التخصص المختاره:",
      searchLevelTitle: "إختر مستوى الطبيب :",
      searchLevelText1: "إختر مستوى الطبيب الذى تريد البحث عنه",
      searchLevelText2: "مستوى الطبيب :",
      searchPriceTitle: "إختر مدي السعر للكشف :",
      searchPriceText1: "السعر المبدئي",
      searchPriceText2: "السعر النهائي",
      searchRateTitle: "إختر مستوى التقيم :",
      searchRateText1: "إختر مستوى الطبيب الذى تريد البحث عنه",
      searchRateText2: "مستوى التقيم :",
      searchReservationTypeTitle: "نوع الكشف :",
      searchReservationTypeText1: "كشف منزلي",
      searchReservationTypeText2: "كشف في العياده",
      loadingKey:"تحميل",
      doctorHasNoScreen1: "ليس هناك أطباء متخصصين مسجلين فى هذا التخصص حتى الآن",
      doctorHasNoScreen2: "ليس هناك طبيب بهذا الاسم",
      doctorHasNoScreen3: "ليس هناك اطباء فى هذه المنطقه",
      doctorHasNoScreen4: "ليس هناك اطباء بهذا الاسم فى هذه المنطقه",
      allAreaKey: "كل المناطق ",
      noReviewsOnDoc: "ليس هناك تقيم عن هذا الطبيب حتى الان",
      reviewsOnDoc1: "التقييم العام من ",
      reviewsOnDoc2: "زائر",
      docAchievement1:"مستمع جيد ",
      docAchievement2:"شرحه مفصل ",
      reservationPrice1: "الكشف :",
      reservationPrice2: "  ريال",
      reservationTime1: "مدة الأنتظار:",
      reservationTime2: " دقيقة دقيقة",
      noTimeAvailableDocScreen: "ليس هناك مواعيد متاح حتى الان",
      reservationBTNDocScreen: "احجز الأن",
      availableToDay: "متاح اليوم من ",
      doctorLoc:"موقع الدكتور",
      docReview:"التقييم الدكتور",
      toKey:"إلى",
      waitingTimeDocDetailedScreenText1: "دقيقة",
      waitingTimeDocDetailedScreenText2: "وقت الانتظار",
      priceDocDetailedScreenText1: " ريال",
      priceDocDetailedScreenText2: "سعر الكشف",
      showOnGoogleMap: "فتح موقع المكان على جوجل ماب",
      noVideo: "ليس هناك فيديو متاح الان",
      noTimeDocDetailedScreen: "ليس هناك مواعيد متاح حاليا",
      timeDocDetailedScreenText1: "اختر ميعاد حجزك",
      timeDocDetailedScreenText2: "الدخول بأسبقية الحضور",
      pointDocDetailedScreenText1: "ستحصل علي ",
      pointDocDetailedScreenText2: " نقطة عند الحجز",
      doctorReview: "تقييم الدكتور",
      placeReview: "التقييم المستشفى",
      doctorInformation: "معلومات عن الدكتور",
      noReviews: "لا توجد تعليقات",
      doctorReviewsTitle: "تقييمات الزائرين",
      doctorDetailedTitle:"بيانات الدكتور",
      changePassScreenTitle: "تغير كلمه السر",
      changePassScreenText1: "كلمه السر الجديدة",
      changePassScreenText2: "أعد كتابة كلمة السر الجديدة",
      changePassScreenText3:  "يجب أن يكون كلمه السر تحتوى على حرف كبير و حرف صغير ورموز خاصه مثل :(@,#,!,&,*,~)و رقم وليس أقل من ٨أحرف",
      deleteAcc:  'مسح الحساب',
      logOut:  'الخروج من الحساب',
      warningLogOut:  'تسجيل الخروج من الحساب',
      warningDeleteAcc:  "مسح الحساب سوف يترتب عليه خساره جميع البينات المسجله وايضا خساره النقاط المكتسبة",
      contDeleteAcc:"استكمال المسح",
      bottomBarItem1: "الحساب الشخصى",
      bottomBarItem2: "الأطباء",
      bottomBarItem3: "الصفحة الرئيسية",
      bottomBarItem4: "مستشفى",
      bottomBarItem5: "البحث المتقدم",
      languageDialogueEN: " الإنجليزية ",
      languageDialogueAR: " العربية ",
      languageDialogueCL: "إختر اللغة",
      languageDialogueBTN:"تغير اللغة",
      languageWelcomeBTN:"change language to english"




}
  };
}